version: "3"
services:
  jupyter:
    build: .
    command: jupyter-notebook --allow-root --ip 0.0.0.0 --port 8888
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    restart:
      always